export const NOTIFY = {
    BCK_PRESSURE_AFTER_STARTUPMSG: 0x100,
    ERROR_REQUEST_SSL_PARAMS: 0x101,
    CREATE_STARTUPMSG_FAILURE: 0x102,
    SEND_STARTUP_MESSAGE_FAILURE: 0x103,
    ERROR_REQUEST_PG_CONNET_PARAMS: 0x104,
    ERROR_SSL_WRONGLY_CONFIGURED: 0x105,
    CREATE_SSLREQUEST_MSG_FAILURE: 0x106,
    BCK_PRESSURE_AFTER_SSLREQUESTMSG: 0x107,
    SEND_SSLREQUEST_MSG_FAILURE: 0x108,
    GOT_DATA_BEFORE_INIT_HANDSHAKE: 0x108,
    BUFFER_STUFFING_ATTACK_MAYBE: 0x109
};
