export type NFY_IOMAN_INITIAL_DONE_TYPE = 'n01';
export type NFY_IOMAN_SOCKET_CONNECT_EVENT_HANDLED_TYPE = 'n02';


export type ERR_IOMAN_NO_INTIALIZER_TYPE = 'e01';
export type ERR_IOMAN_NO_INTIALIZE_FAIL_TYPE = 'e02';
export type ERR_IOMAN_NO_PROTOCOL_HANDLER_TYPE = 'e03';


export const ERR_IOMAN_NO_INTIALIZER: ERR_IOMAN_NO_INTIALIZER_TYPE = 'e01';
export const ERR_IOMAN_NO_INTIALIZE_FAIL: ERR_IOMAN_NO_INTIALIZE_FAIL_TYPE = 'e02';
export const ERR_IOMAN_NO_PROTOCOL_HANDLER: ERR_IOMAN_NO_PROTOCOL_HANDLER_TYPE = 'e03';

export const NFY_IOMAN_INITIAL_DONE: NFY_IOMAN_INITIAL_DONE_TYPE = 'n01';
export const NFY_IOMAN_SOCKET_CONNECT_EVENT_HANDLED: NFY_IOMAN_SOCKET_CONNECT_EVENT_HANDLED_TYPE = 'n02';

